name: Generate SBOM
description: Generate an SBOM for the OCI image

inputs:
  image-ref:
    description: 'The reference to the OCI image to generate an SBOM for'
    required: true
  cosign-private-key:
    description: 'The private key to use for signing the SBOM'
    required: true
  cosign-key-passphrase:
    description: 'The passphrase for the private key'
    required: true

outputs:
  sbom-path:
    description: 'The path to the generated SBOM'
    value: ${{ steps.generate-sbom.outputs.OUTPUT_PATH }}

runs:
  using: 'composite'
  steps:
    - name: Setup Syft
      id: setup-syft
      uses: anchore/sbom-action/download-syft@f325610c9f50a54015d37c8d16cb3b0e2c8f4de0 # v0

    - name: Generate SBOM
      id: generate-sbom
      shell: bash
      env:
        IMAGE_REF: ${{ inputs.image-ref }}
        SYFT_CMD: ${{ steps.setup-syft.outputs.cmd }}
      run: |
        systemctl start --user podman.socket
        DESTINATION=$(mktemp -d)/sbom.json
        $SYFT_CMD $IMAGE_REF -o spdx-json=$DESTINATION
        echo "OUTPUT_PATH=$DESTINATION" >> $GITHUB_OUTPUT

    - name: Setup Cosign
      id: setup-cosign
      uses: sigstore/cosign-installer@d7d6bc7722e3daa8354c50bcb52f4837da5e9b6a # v3

    - name: Attach SBOM
      id: attach-sbom
      shell: bash
      env:
        SBOM_PATH: ${{ steps.generate-sbom.outputs.OUTPUT_PATH }}
        COSIGN_PRIVATE_KEY: ${{ inputs.cosign-private-key }}
        COSIGN_PASSWORD: ${{ inputs.cosign-key-passphrase }}
        IMAGE_REF: ${{ inputs.image-ref }}
      run: |
        cd $(dirname $SBOM_PATH)
        cosign attest -y \
          --predicate ./sbom.json \
          --type spdxjson \
          --key env://COSIGN_PRIVATE_KEY \
          $IMAGE_REF
