name: Integration Tests

on:
  workflow_call:
    inputs:
      image-ref:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Pull Image
        env:
          IMAGE_REF: ${{ inputs.image-ref }}
        run: |
          podman pull "${IMAGE_REF}"
