name: Build Image

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  actions: read
  id-token: write
  packages: write

jobs:
  build:
    uses: ./.github/workflows/_build.yml
    with:
      image-name: bootc/qemu-base
      os-version: stream10
