name: Build Image

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  schedule:
    # On the 1st and 15th of the month at midnight
    - cron: '0 0 1,15 * *'

permissions:
  contents: read
  actions: read
  id-token: write
  packages: write

concurrency:
  group: build-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/_build.yml
    secrets: inherit
    strategy:
      fail-fast: false
      matrix:
        target: [qemu]
    with:
      image-name: bootc/${{ matrix.target }}/centos-base
      os-version: stream10
